// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function CreateCartridge(arg1:string,arg2:string):Promise<store.Cartridge>;

export function CreateConfig(arg1:string,arg2:string,arg3:number):Promise<main.CreateResult>;

export function DeleteCartridge(arg1:number):Promise<void>;

export function DeleteConfig(arg1:number):Promise<void>;

export function GetConfigCombos(arg1:number,arg2:Array<string>,arg3:number,arg4:number):Promise<main.ComboPage>;

export function GetConfigDetail(arg1:number):Promise<main.ConfigDetail>;

export function ListCartridges():Promise<Array<store.Cartridge>>;

export function ListConfigs():Promise<Array<store.Config>>;

export function ListPieces():Promise<Array<main.PieceInfo>>;

export function RenameConfig(arg1:number,arg2:string):Promise<void>;

export function ReorderCartridges(arg1:Array<number>):Promise<void>;

export function ReorderConfigs(arg1:Array<number>):Promise<void>;

export function UpdateCartridge(arg1:number,arg2:string,arg3:string):Promise<store.Cartridge>;

export function UpdateConfig(arg1:number,arg2:string,arg3:string,arg4:number):Promise<main.CreateResult>;
