// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCartridge(arg1, arg2) {
  return window['go']['main']['App']['CreateCartridge'](arg1, arg2);
}

export function CreateConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConfig'](arg1, arg2, arg3);
}

export function DeleteCartridge(arg1) {
  return window['go']['main']['App']['DeleteCartridge'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function GetConfigCombos(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetConfigCombos'](arg1, arg2, arg3, arg4);
}

export function GetConfigDetail(arg1) {
  return window['go']['main']['App']['GetConfigDetail'](arg1);
}

export function ListCartridges() {
  return window['go']['main']['App']['ListCartridges']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListPieces() {
  return window['go']['main']['App']['ListPieces']();
}

export function RenameConfig(arg1, arg2) {
  return window['go']['main']['App']['RenameConfig'](arg1, arg2);
}

export function ReorderCartridges(arg1) {
  return window['go']['main']['App']['ReorderCartridges'](arg1);
}

export function ReorderConfigs(arg1) {
  return window['go']['main']['App']['ReorderConfigs'](arg1);
}

export function UpdateCartridge(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCartridge'](arg1, arg2, arg3);
}

export function UpdateConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2, arg3, arg4);
}
